#!/command/with-contenv bash
# shellcheck shell=bash

set -e

. /bin/common.sh

cd /app || exit 1

log_info 'Starting backend ...'

if [ "${DEVELOPMENT:-}" = 'true' ]; then
	s6-setuidgid "$PUID:$PGID" yarn install
	exec s6-setuidgid "$PUID:$PGID" bash -c "export HOME=$NPMHOME;bun -b --watch ./index.js"
else
	while :
	do
		s6-setuidgid "$PUID:$PGID" bash -c "export HOME=$NPMHOME;bun -b ./index.js"
		sleep 1
	done
fi
